name: Render and deploy Quarto site

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.8.11"

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.2"

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(
            c("knitr","rmarkdown","ggplot2","dplyr"),
            repos="https://cloud.r-project.org"
          )'

      - name: Render site
        run: quarto render --no-preview

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _site
